# Generated by Django 4.2.16 on 2025-03-05 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wandercritic", "0004_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="reported_by",
        ),
        migrations.RemoveField(
            model_name="report",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_filed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("inappropriate", "Inappropriate Content"),
                    ("spam", "Spam"),
                    ("misinformation", "Misinformation"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
