# Generated by Django 4.2.16 on 2025-03-05 05:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "wandercritic",
            "0005_remove_report_reported_by_remove_report_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="placecategory",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="placeimage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="place",
            name="best_time_to_visit",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="place",
            name="categories",
            field=models.ManyToManyField(
                related_name="places", to="wandercritic.placecategory"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="getting_there",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="place",
            name="highlights",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="place",
            name="history",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="place",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="tags",
            field=models.ManyToManyField(related_name="places", to="wandercritic.tag"),
        ),
        migrations.AlterField(
            model_name="place",
            name="tips",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="caption",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="report",
            name="resolved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="travelagentapplication",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="travelagentapplication",
            name="experience",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="travelagentapplication",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
    ]
