# Generated by Django 4.2.16 on 2025-03-05 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "wandercritic",
            "0006_placecategory_description_placeimage_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="place",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="place",
            name="best_time_to_visit",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="getting_there",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="highlights",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="history",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="tips",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="placecategory",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="travelagentapplication",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="travelagentapplication",
            name="experience",
            field=models.TextField(
                help_text="Describe your travel industry experience"
            ),
        ),
        migrations.AlterField(
            model_name="travelagentapplication",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Fair"),
                            (3, "3 - Good"),
                            (4, "4 - Very Good"),
                            (5, "5 - Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wandercritic.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("place", "user")},
            },
        ),
    ]
