# Generated by Django 4.2.16 on 2025-03-05 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wandercritic", "0007_place_average_rating_place_total_ratings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="rating",
        ),
    ]
