# Generated by Django 5.1.6 on 2025-03-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wandercritic", "0009_websitereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="company_website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
