# Generated by Django 5.1.6 on 2025-03-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wandercritic", "0010_user_company_name_user_company_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="content_type",
            field=models.CharField(
                choices=[("place", "Place"), ("review", "Review")],
                default="place",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="wandercritic.review",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="wandercritic.place",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("inappropriate", "Inappropriate Content"),
                    ("spam", "Spam"),
                    ("misinformation", "Misinformation"),
                    ("harassment", "Harassment"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
