# Generated by Django 5.1.6 on 2025-03-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wandercritic",
            "0011_report_content_type_report_review_alter_report_place_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="review",
        ),
        migrations.AlterField(
            model_name="report",
            name="content_type",
            field=models.CharField(
                choices=[("place", "Place"), ("review", "Review"), ("user", "User")],
                default="place",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="wandercritic.place",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("inappropriate", "Inappropriate Content"),
                    ("spam", "Spam"),
                    ("misinformation", "Misinformation"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
