# Generated by Django 5.1.6 on 2025-03-07 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandercritic', '0012_remove_report_review_alter_report_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='wandercritic.review'),
        ),
    ]
