# Generated by Django 5.1.6 on 2025-03-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandercritic', '0013_report_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('place', 'Place'), ('user', 'User'), ('bug', 'Bug')], default='place', max_length=20),
        ),
    ]
