# Generated by Django 5.1.6 on 2025-03-09 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandercritic', '0014_alter_report_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='wandercritic.place'),
        ),
    ]
