# Generated by Django 5.1.6 on 2025-03-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandercritic', '0015_report_url_alter_report_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget for the trip in GBP', max_digits=10, null=True),
        ),
    ]
